[package]
name = "datadir"
version = "0.1.0"
edition = "2024"
authors = ["Cl√©ment Michaud"]
description = "Create a datadir available during the test to dump golden files."
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"